// Catálogo Citadel — fuente: grimify.app (github.com/NathanHealea/grimify.app)
export const CITADEL_CATALOG = [
  { name: 'Abaddon Black', type: 'base', hex: "#231f20" },
  { name: 'Averland Sunset', type: 'base', hex: "#fdb825" },
  { name: 'Balthasar Gold', type: 'base', hex: "#a47552" },
  { name: 'Bugmans Glow', type: 'base', hex: "#834f44" },
  { name: 'Caledor Sky', type: 'base', hex: "#396e9e" },
  { name: 'Caliban Green', type: 'base', hex: "#00401f" },
  { name: 'Castellan Green', type: 'base', hex: "#314821" },
  { name: 'Celestra Grey', type: 'base', hex: "#90a8a8" },
  { name: 'Corax White', type: 'base', hex: "#f0f0f0" },
  { name: 'Corvus Black', type: 'base', hex: "#171314" },
  { name: 'Daemonette Hide', type: 'base', hex: "#696684" },
  { name: 'Death Guard Green', type: 'base', hex: "#848a66" },
  { name: 'Deathworld Forest', type: 'base', hex: "#5c6730" },
  { name: 'Dryad Bark', type: 'base', hex: "#33312d" },
  { name: 'Grey Knights Steel', type: 'base', hex: "#8b9fa1" },
  { name: 'Grey Seer', type: 'base', hex: "#a2a5a7" },
  { name: 'Hobgrot Hide', type: 'base', hex: "#b8845b" },
  { name: 'Incubi Darkness', type: 'base', hex: "#0b474a" },
  { name: 'Iron Hands Steel', type: 'base', hex: "#44423f" },
  { name: 'Iron Warriors', type: 'base', hex: "#535150" },
  { name: 'Jokaero Orange', type: 'base', hex: "#ee3823" },
  { name: 'Kantor Blue', type: 'base', hex: "#002151" },
  { name: 'Khorne Red', type: 'base', hex: "#6a0001" },
  { name: 'Leadbelcher', type: 'base', hex: "#888d8f" },
  { name: 'Lupercal Green', type: 'base', hex: "#002e2d" },
  { name: 'Macragge Blue', type: 'base', hex: "#0d407f" },
  { name: 'Mechanicus Standard Grey', type: 'base', hex: "#3d4b4d" },
  { name: 'Mephiston Red', type: 'base', hex: "#9a1115" },
  { name: 'Morghast Bone', type: 'base', hex: "#c7b68a" },
  { name: 'Mournfang Brown', type: 'base', hex: "#640909" },
  { name: 'Naggaroth Night', type: 'base', hex: "#3d3354" },
  { name: 'Night Lords Blue', type: 'base', hex: "#002b5c" },
  { name: 'Nocturne Green', type: 'base', hex: "#162a1f" },
  { name: 'Orruk Flesh', type: 'base', hex: "#8cc276" },
  { name: 'Phoenician Purple', type: 'base', hex: "#440052" },
  { name: 'Rakarth Flesh', type: 'base', hex: "#a29e91" },
  { name: 'Retributor Armour', type: 'base', hex: "#c39e81" },
  { name: 'Rhinox Hide', type: 'base', hex: "#493435" },
  { name: 'Screamer Pink', type: 'base', hex: "#7c1645" },
  { name: 'Screaming Bell', type: 'base', hex: "#c16f45" },
  { name: 'Steel Legion Drab', type: 'base', hex: "#5e5134" },
  { name: 'Stegadon Scale Green', type: 'base', hex: "#074863" },
  { name: 'The Fang', type: 'base', hex: "#436174" },
  { name: 'Thousand Sons Blue', type: 'base', hex: "#18abcc" },
  { name: 'Waaagh! Flesh', type: 'base', hex: "#1f5429" },
  { name: 'Warplock Bronze', type: 'base', hex: "#927d7b" },
  { name: 'Wraith Bone', type: 'base', hex: "#dbd1b2" },
  { name: 'XV-88', type: 'base', hex: "#72491e" },
  { name: 'Zandri Dust', type: 'base', hex: "#9e915c" },
  { name: 'Administratum Grey', type: 'layer', hex: "#949b95" },
  { name: 'Ahriman Blue', type: 'layer', hex: "#1f8c9c" },
  { name: 'Alaitoc Blue', type: 'layer', hex: "#295788" },
  { name: 'Altdorf Guard Blue', type: 'layer', hex: "#1f56a7" },
  { name: 'Auric Armour Gold', type: 'layer', hex: "#e8bc6d" },
  { name: 'Balor Brown', type: 'layer', hex: "#8b5910" },
  { name: 'Baneblade Brown', type: 'layer', hex: "#937f6d" },
  { name: 'Bestigor Flesh', type: 'layer', hex: "#d38a57" },
  { name: 'Brass Scorpion', type: 'layer', hex: "#b7885f" },
  { name: 'Cadian Fleshtone', type: 'layer', hex: "#c77958" },
  { name: 'Calgar Blue', type: 'layer', hex: "#4272b8" },
  { name: 'Dark Reaper', type: 'layer', hex: "#3b5150" },
  { name: 'Dawnstone', type: 'layer', hex: "#70756e" },
  { name: 'Deathclaw Brown', type: 'layer', hex: "#b36853" },
  { name: 'Deepkin Flesh', type: 'layer', hex: "#95bab8" },
  { name: 'Doombull Brown', type: 'layer', hex: "#5d0009" },
  { name: 'Elysian Green', type: 'layer', hex: "#748f39" },
  { name: 'Emperors Children', type: 'layer', hex: "#b94278" },
  { name: 'Eshin Grey', type: 'layer', hex: "#4a4f52" },
  { name: 'Evil Sunz Scarlet', type: 'layer', hex: "#c2191f" },
  { name: 'Fenrisian Grey', type: 'layer', hex: "#719bb7" },
  { name: 'Fire Dragon Bright', type: 'layer', hex: "#f58652" },
  { name: 'Flash Gitz Yellow', type: 'layer', hex: "#fff200" },
  { name: 'Flayed One Flesh', type: 'layer', hex: "#f0d9b8" },
  { name: 'Fulgurite Copper', type: 'layer', hex: "#9d7050" },
  { name: 'Gauss Blaster Green', type: 'layer', hex: "#7fc1a5" },
  { name: 'Gehenna\'s Gold', type: 'layer', hex: "#dba674" },
  { name: 'Genestealer Purple', type: 'layer', hex: "#7761ab" },
  { name: 'Gorthor Brown', type: 'layer', hex: "#654741" },
  { name: 'Hashut Copper', type: 'layer', hex: "#b77647" },
  { name: 'Hoeth Blue', type: 'layer', hex: "#4c7fb4" },
  { name: 'Ironbreaker', type: 'layer', hex: "#a1a6a9" },
  { name: 'Kabalite Green', type: 'layer', hex: "#038c67" },
  { name: 'Karak Stone', type: 'layer', hex: "#bb9662" },
  { name: 'Kislev Flesh', type: 'layer', hex: "#d6a875" },
  { name: 'Knight-Questor Flesh', type: 'layer', hex: "#c99064" },
  { name: 'Krieg Khaki', type: 'layer', hex: "#c3b17d" },
  { name: 'Liberator Gold', type: 'layer', hex: "#d3b587" },
  { name: 'Loren Forest', type: 'layer', hex: "#50702d" },
  { name: 'Lothern Blue', type: 'layer', hex: "#34a2cf" },
  { name: 'Moot Green', type: 'layer', hex: "#52b244" },
  { name: 'Nurgling Green', type: 'layer', hex: "#849c63" },
  { name: 'Ogryn Camo', type: 'layer', hex: "#9da94b" },
  { name: 'Pallid Wych Flesh', type: 'layer', hex: "#cdcebe" },
  { name: 'Phalanx Yellow', type: 'layer', hex: "#ffe200" },
  { name: 'Pink Horror', type: 'layer', hex: "#90305d" },
  { name: 'Runefang Steel', type: 'layer', hex: "#c3cace" },
  { name: 'Runelord Brass', type: 'layer', hex: "#b6a89a" },
  { name: 'Russ Grey', type: 'layer', hex: "#547588" },
  { name: 'Screaming Skull', type: 'layer', hex: "#d2d4a2" },
  { name: 'Skarsnik Green', type: 'layer', hex: "#5f9370" },
  { name: 'Skavenblight Dinge', type: 'layer', hex: "#47413b" },
  { name: 'Skrag Brown', type: 'layer', hex: "#90490f" },
  { name: 'Skullcrusher Brass', type: 'layer', hex: "#f1c78e" },
  { name: 'Slaanesh Grey', type: 'layer', hex: "#8e8c97" },
  { name: 'Sotek Green', type: 'layer', hex: "#0b6974" },
  { name: 'Sons of Horus Green', type: 'layer', hex: "#00545e" },
  { name: 'Squig Orange', type: 'layer', hex: "#aa4f44" },
  { name: 'Stormhost Silver', type: 'layer', hex: "#bbc6c9" },
  { name: 'Stormvermin Fur', type: 'layer', hex: "#736b65" },
  { name: 'Straken Green', type: 'layer', hex: "#628126" },
  { name: 'Sybarite Green', type: 'layer', hex: "#30a56c" },
  { name: 'Sycorax Bronze', type: 'layer', hex: "#cbb394" },
  { name: 'Tallarn Sand', type: 'layer', hex: "#a67610" },
  { name: 'Tau Light Ochre', type: 'layer', hex: "#bf6e1d" },
  { name: 'Teclis Blue', type: 'layer', hex: "#317ec1" },
  { name: 'Temple Guard Blue', type: 'layer', hex: "#339a8d" },
  { name: 'Thunderhawk Blue', type: 'layer', hex: "#417074" },
  { name: 'Troll Slayer Orange', type: 'layer', hex: "#f36d2d" },
  { name: 'Tuskgor Fur', type: 'layer', hex: "#883636" },
  { name: 'Ulthuan Grey', type: 'layer', hex: "#c7e0d9" },
  { name: 'Ungor Flesh', type: 'layer', hex: "#d6a766" },
  { name: 'Ushabti Bone', type: 'layer', hex: "#bbbb7f" },
  { name: 'Vulkan Green', type: 'layer', hex: "#223c2e" },
  { name: 'Warboss Green', type: 'layer', hex: "#3e805d" },
  { name: 'Warpfiend Grey', type: 'layer', hex: "#6b6a74" },
  { name: 'Warpstone Glow', type: 'layer', hex: "#1e7331" },
  { name: 'Wazdakka Red', type: 'layer', hex: "#8c0a0c" },
  { name: 'White Scar', type: 'layer', hex: "#ffffff" },
  { name: 'Wild Rider Red', type: 'layer', hex: "#ea2f28" },
  { name: 'Word Bearers Red', type: 'layer', hex: "#620104" },
  { name: 'Xereus Purple', type: 'layer', hex: "#471f5f" },
  { name: 'Yriel Yellow', type: 'layer', hex: "#ffda00" },
  { name: 'Zamesi Desert', type: 'layer', hex: "#dda026" },
  { name: 'Baharroth Blue', type: 'layer', hex: "#58c1cd" },
  { name: 'Blue Horror', type: 'layer', hex: "#a2bad2" },
  { name: 'Dechala Lilac', type: 'layer', hex: "#b69fcc" },
  { name: 'Dorn Yellow', type: 'layer', hex: "#fff200" },
  { name: 'Fulgrim Pink', type: 'layer', hex: "#f4afcd" },
  { name: 'Gauss Blaster Green', type: 'layer', hex: "#84c3aa" },
  { name: 'Krieg Khaki', type: 'layer', hex: "#c0bd81" },
  { name: 'Lugganath Orange', type: 'layer', hex: "#f79e86" },
  { name: 'Aeldari Emerald', type: 'contrast', hex: "#00694a" },
  { name: 'Aethermatic Blue', type: 'contrast', hex: "#73c2c6" },
  { name: 'Aggaros Dunes', type: 'contrast', hex: "#cda059" },
  { name: 'Akhelian Green', type: 'contrast', hex: "#2f726a" },
  { name: 'Apothecary White', type: 'contrast', hex: "#d3e0e6" },
  { name: 'Asurmen Blue', type: 'contrast', hex: "#2948a5" },
  { name: 'Baal Red', type: 'contrast', hex: "#8b1a1a" },
  { name: 'Bad Moon Yellow', type: 'contrast', hex: "#e8c820" },
  { name: 'Basilicanum Grey', type: 'contrast', hex: "#5b5856" },
  { name: 'Black Legion', type: 'contrast', hex: "#1c1b18" },
  { name: 'Black Templar', type: 'contrast', hex: "#171717" },
  { name: 'Blood Angels Red', type: 'contrast', hex: "#c91b1c" },
  { name: 'Briar Queen Chill', type: 'contrast', hex: "#8fbcc8" },
  { name: 'Celestium Blue', type: 'contrast', hex: "#4898d0" },
  { name: 'Creed Camo', type: 'contrast', hex: "#5c6f30" },
  { name: 'Cygor Brown', type: 'contrast', hex: "#5e3a2c" },
  { name: 'Dark Angels Green', type: 'contrast', hex: "#003820" },
  { name: 'Darkoath Flesh', type: 'contrast', hex: "#c88860" },
  { name: 'Doomfire Magenta', type: 'contrast', hex: "#b81860" },
  { name: 'Dreadful Visage', type: 'contrast', hex: "#e8dba0" },
  { name: 'Flesh Tearers Red', type: 'contrast', hex: "#7d1119" },
  { name: 'Frostheart', type: 'contrast', hex: "#9bbfd0" },
  { name: 'Fyreslayer Flesh', type: 'contrast', hex: "#d07050" },
  { name: 'Garaghak\'s Sewer', type: 'contrast', hex: "#585540" },
  { name: 'Gore-grunta Fur', type: 'contrast', hex: "#7a3b20" },
  { name: 'Gryph-charger Grey', type: 'contrast', hex: "#5b6e7c" },
  { name: 'Gryph-hound Orange', type: 'contrast', hex: "#e36820" },
  { name: 'Guilliman Flesh', type: 'contrast', hex: "#d09078" },
  { name: 'Gutrippa Flesh', type: 'contrast', hex: "#809828" },
  { name: 'Hexwraith Flame', type: 'contrast', hex: "#57a862" },
  { name: 'Imperial Fist', type: 'contrast', hex: "#f0c020" },
  { name: 'Ironjawz Yellow', type: 'contrast', hex: "#d8a820" },
  { name: 'Iyanden Yellow', type: 'contrast', hex: "#edba1b" },
  { name: 'Karandras Green', type: 'contrast', hex: "#2c5c28" },
  { name: 'Kroxigor Scales', type: 'contrast', hex: "#287080" },
  { name: 'Leviadon Blue', type: 'contrast', hex: "#1a3050" },
  { name: 'Leviathan Purple', type: 'contrast', hex: "#5c3078" },
  { name: 'Luxion Purple', type: 'contrast', hex: "#7030a0" },
  { name: 'Magmadroth Flame', type: 'contrast', hex: "#d84010" },
  { name: 'Magos Purple', type: 'contrast', hex: "#9878b0" },
  { name: 'Mantis Warriors Green', type: 'contrast', hex: "#509820" },
  { name: 'Militarum Green', type: 'contrast', hex: "#707848" },
  { name: 'Nazdreg Yellow', type: 'contrast', hex: "#c89020" },
  { name: 'Nighthaunt Gloom', type: 'contrast', hex: "#587878" },
  { name: 'Ork Flesh', type: 'contrast', hex: "#449040" },
  { name: 'Plaguebearer Flesh', type: 'contrast', hex: "#b8c068" },
  { name: 'Pylar Glacier', type: 'contrast', hex: "#a0c8e0" },
  { name: 'Ratling Grime', type: 'contrast', hex: "#6b5838" },
  { name: 'Shyish Purple', type: 'contrast', hex: "#503068" },
  { name: 'Sigvald Burgundy', type: 'contrast', hex: "#6b1830" },
  { name: 'Skeleton Horde', type: 'contrast', hex: "#c4a85a" },
  { name: 'Snakebite Leather', type: 'contrast', hex: "#a86818" },
  { name: 'Space Wolves Grey', type: 'contrast', hex: "#6890a8" },
  { name: 'Stormfiend', type: 'contrast', hex: "#3c5060" },
  { name: 'Striking Scorpion Green', type: 'contrast', hex: "#40a830" },
  { name: 'Talassar Blue', type: 'contrast', hex: "#2065a0" },
  { name: 'Terradon Turquoise', type: 'contrast', hex: "#10a0a0" },
  { name: 'Ultramarine Blue', type: 'contrast', hex: "#203898" },
  { name: 'Volupus Pink', type: 'contrast', hex: "#982858" },
  { name: 'Warp Lightning', type: 'contrast', hex: "#30b030" },
  { name: 'Wyldwood', type: 'contrast', hex: "#4a3020" },
  { name: 'Agrax Earthshade', type: 'shade', hex: "#63452a" },
  { name: 'Athonian Camoshade', type: 'shade', hex: "#6b6b2e" },
  { name: 'Berserker Bloodshade', type: 'shade', hex: "#8b1a1a" },
  { name: 'Biel-Tan Green', type: 'shade', hex: "#1b7d3f" },
  { name: 'Carroburg Crimson', type: 'shade', hex: "#a8324d" },
  { name: 'Casandora Yellow', type: 'shade', hex: "#fdba12" },
  { name: 'Coelia Greenshade', type: 'shade', hex: "#0d7266" },
  { name: 'Drakenhof Nightshade', type: 'shade', hex: "#2b4b6f" },
  { name: 'Druchii Violet', type: 'shade', hex: "#6b395f" },
  { name: 'Fuegan Orange', type: 'shade', hex: "#c75b23" },
  { name: 'Kroak Green', type: 'shade', hex: "#2b6b4a" },
  { name: 'Mortarion Grime', type: 'shade', hex: "#5c5830" },
  { name: 'Nuln Oil', type: 'shade', hex: "#2b2b2b" },
  { name: 'Poxwalker', type: 'shade', hex: "#8b7d4a" },
  { name: 'Reikland Fleshshade', type: 'shade', hex: "#ca6c4d" },
  { name: 'Seraphim Sepia', type: 'shade', hex: "#d7a94b" },
  { name: 'Soulblight Grey', type: 'shade', hex: "#7a7a7a" },
  { name: 'Targor Rageshade', type: 'shade', hex: "#7d3352" },
  { name: 'Tyran Blue', type: 'shade', hex: "#2b5890" },
  { name: 'Abaddon Black', type: 'air', hex: "#231f20" },
  { name: 'Administratum Grey', type: 'air', hex: "#949b95" },
  { name: 'Averland Sunset', type: 'air', hex: "#fdb825" },
  { name: 'Baneblade Brown', type: 'air', hex: "#937f6d" },
  { name: 'Cadian Fleshtone', type: 'air', hex: "#c77958" },
  { name: 'Caledor Sky', type: 'air', hex: "#396e9e" },
  { name: 'Caliban Green', type: 'air', hex: "#00401f" },
  { name: 'Castellan Green', type: 'air', hex: "#314821" },
  { name: 'Corax White', type: 'air', hex: "#f0f0f0" },
  { name: 'Dawnstone', type: 'air', hex: "#70756e" },
  { name: 'Dryad Bark', type: 'air', hex: "#33312d" },
  { name: 'Elysian Green', type: 'air', hex: "#748f39" },
  { name: 'Evil Sunz Scarlet', type: 'air', hex: "#c2191f" },
  { name: 'Fenrisian Grey', type: 'air', hex: "#719bb7" },
  { name: 'Flash Gitz Yellow', type: 'air', hex: "#fff200" },
  { name: 'Jokaero Orange', type: 'air', hex: "#ee3823" },
  { name: 'Kabalite Green', type: 'air', hex: "#038c67" },
  { name: 'Kantor Blue', type: 'air', hex: "#002151" },
  { name: 'Khorne Red', type: 'air', hex: "#6a0001" },
  { name: 'Kislev Flesh', type: 'air', hex: "#d6a875" },
  { name: 'Lothern Blue', type: 'air', hex: "#34a2cf" },
  { name: 'Macragge Blue', type: 'air', hex: "#0d407f" },
  { name: 'Mechanicus Standard Grey', type: 'air', hex: "#3d4b4d" },
  { name: 'Mephiston Red', type: 'air', hex: "#9a1115" },
  { name: 'Moot Green', type: 'air', hex: "#52b244" },
  { name: 'Mournfang Brown', type: 'air', hex: "#640909" },
  { name: 'Naggaroth Night', type: 'air', hex: "#3d3354" },
  { name: 'Ogryn Camo', type: 'air', hex: "#9da94b" },
  { name: 'Ratskin Flesh', type: 'air', hex: "#cf8764" },
  { name: 'Rhinox Hide', type: 'air', hex: "#493435" },
  { name: 'Screamer Pink', type: 'air', hex: "#7c1645" },
  { name: 'Stegadon Scale Green', type: 'air', hex: "#074863" },
  { name: 'Steel Legion Drab', type: 'air', hex: "#5e5134" },
  { name: 'Sybarite Green', type: 'air', hex: "#30a56c" },
  { name: 'Tallarn Sand', type: 'air', hex: "#a67610" },
  { name: 'Teclis Blue', type: 'air', hex: "#317ec1" },
  { name: 'Thousand Sons Blue', type: 'air', hex: "#18abcc" },
  { name: 'Troll Slayer Orange', type: 'air', hex: "#f36d2d" },
  { name: 'Ulthuan Grey', type: 'air', hex: "#c7e0d9" },
  { name: 'Ushabti Bone', type: 'air', hex: "#bbbb7f" },
  { name: 'Warpstone Glow', type: 'air', hex: "#1e7331" },
  { name: 'XV-88', type: 'air', hex: "#72491e" },
  { name: 'Xereus Purple', type: 'air', hex: "#471f5f" },
  { name: 'Yriel Yellow', type: 'air', hex: "#ffda00" },
  { name: 'Zandri Dust', type: 'air', hex: "#9e915c" },
  { name: 'Astorath Red', type: 'dry', hex: "#a02828" },
  { name: 'Dawnstone', type: 'dry', hex: "#70756e" },
  { name: 'Eldar Flesh', type: 'dry', hex: "#d0a870" },
  { name: 'Etherium Blue', type: 'dry', hex: "#95b0c9" },
  { name: 'Golden Griffon', type: 'dry', hex: "#d4a038" },
  { name: 'Golgfag Brown', type: 'dry', hex: "#8e4c2c" },
  { name: 'Hexos Palesun', type: 'dry', hex: "#f5e34b" },
  { name: 'Hoeth Blue', type: 'dry', hex: "#4c7fb4" },
  { name: 'Imrik Blue', type: 'dry', hex: "#2c8cb0" },
  { name: 'Longbeard Grey', type: 'dry', hex: "#aca89e" },
  { name: 'Lucius Lilac', type: 'dry', hex: "#b090c0" },
  { name: 'Necron Compound', type: 'dry', hex: "#a4a9ad" },
  { name: 'Niblet Green', type: 'dry', hex: "#62a83d" },
  { name: 'Nurgling Green', type: 'dry', hex: "#849c63" },
  { name: 'Praxeti White', type: 'dry', hex: "#f0ede6" },
  { name: 'Ryza Rust', type: 'dry', hex: "#e77c30" },
  { name: 'Skink Blue', type: 'dry', hex: "#5eadb8" },
  { name: 'Stormfang', type: 'dry', hex: "#5a8b9a" },
  { name: 'Sylvaneth Bark', type: 'dry', hex: "#5b4a3c" },
  { name: 'Terminatus Stone', type: 'dry', hex: "#bdb598" },
  { name: 'Tyrant Skull', type: 'dry', hex: "#cbc091" },
  { name: 'Underhive Ash', type: 'dry', hex: "#cbc7b6" },
  { name: 'Wrack White', type: 'dry', hex: "#e8e6e0" },
  { name: 'Chaos Black', type: 'spray', hex: "#101010" },
  { name: 'Corax White', type: 'spray', hex: "#f0f0f0" },
  { name: 'Death Guard Green', type: 'spray', hex: "#848a66" },
  { name: 'Grey Seer', type: 'spray', hex: "#a2a5a7" },
  { name: 'Leadbelcher', type: 'spray', hex: "#888d8f" },
  { name: 'Macragge Blue', type: 'spray', hex: "#0d407f" },
  { name: 'Mechanicus Standard Grey', type: 'spray', hex: "#3d4b4d" },
  { name: 'Mephiston Red', type: 'spray', hex: "#9a1115" },
  { name: 'Retributor Armour', type: 'spray', hex: "#c39e81" },
  { name: 'White Scar', type: 'spray', hex: "#ffffff" },
  { name: 'Wraithbone', type: 'spray', hex: "#dbd1b2" },
  { name: 'Zandri Dust', type: 'spray', hex: "#9e915c" },
  { name: 'Blood for the Blood God', type: 'technical', hex: "#6b0002" },
  { name: 'Nihilakh Oxide', type: 'technical', hex: "#6cb8a0" },
  { name: 'Nurgle\'s Rot', type: 'technical', hex: "#9bb33c" },
  { name: 'Tesseract Glow', type: 'technical', hex: "#49b04a" },
  { name: 'Typhus Corrosion', type: 'technical', hex: "#473b2b" },
  { name: 'Barak-Nar Burgundy', type: 'base', hex: "#451636" },
  { name: 'Bloodreaver Flesh', type: 'layer', hex: "#6a4848" },
  { name: 'Bugman\'s Glow', type: 'base', hex: "#845045" },
  { name: 'Catachan Fleshtone', type: 'base', hex: "#442b25" },
  { name: 'Ceramite White', type: 'base', hex: "#ffffff" },
  { name: 'Death Korps Drab', type: 'base', hex: "#3d4539" },
  { name: 'Emperor\'s Children', type: 'layer', hex: "#b94278" },
  { name: 'Ionrach Skin', type: 'base', hex: "#97a384" },
  { name: 'Kakophoni Purple', type: 'layer', hex: "#8869ae" },
  { name: 'Thondia Brown', type: 'base', hex: "#54302a" },
  { name: 'Canoptek Alloy', type: 'layer', hex: "#c0a870" },
  { name: 'Castellax Bronze', type: 'layer', hex: "#907050" },
  { name: 'Agrax Earthshade Gloss', type: 'shade', hex: "#5a543c" },
  { name: 'Cryptek Armourshade Gloss', type: 'shade', hex: "#3a5050" },
  { name: 'Nuln Oil Gloss', type: 'shade', hex: "#151203" },
  { name: 'Reikland Fleshshade Gloss', type: 'shade', hex: "#a34529" },
  { name: 'Changeling Pink', type: 'dry', hex: "#f4afce" },
  { name: 'Chronus Blue', type: 'dry', hex: "#6e97cf" },
  { name: 'Hellion Green', type: 'dry', hex: "#83c3a9" },
  { name: 'Kindleflame', type: 'dry', hex: "#efb494" },
  { name: 'Sigmarite', type: 'dry', hex: "#dac38d" },
  { name: 'Verminlord Hide', type: 'dry', hex: "#773a37" },
  { name: 'Ardcoat', type: 'technical', hex: "#f0f0f0" },
  { name: 'Contrast Medium', type: 'technical', hex: "#f0f0f0" },
  { name: 'Lahmian Medium', type: 'technical', hex: "#f0f0f0" },
  { name: 'Mordant Earth', type: 'technical', hex: "#1a1a18" },
  { name: 'Nurgles Rot', type: 'technical', hex: "#9d8c30" },
  { name: 'Soulstone Blue', type: 'technical', hex: "#294c86" },
  { name: 'Spiritstone Red', type: 'technical', hex: "#fd5d3d" },
  { name: 'Stormshield', type: 'technical', hex: "#f0f0f0" },
  { name: 'Waystone Green', type: 'technical', hex: "#018675" },
  { name: 'Bloodletter', type: 'technical', hex: "#cb2924" },
  { name: 'Guilliman Blue', type: 'technical', hex: "#2e83c6" },
  { name: 'Lamenters Yellow', type: 'technical', hex: "#fbf44c" },
  { name: 'Waywatcher Green', type: 'technical', hex: "#78b04b" },
]

// Lookup rápido por nombre para el modal
export const PAINT_COLORS = { 'Citadel': {} }
for (const p of CITADEL_CATALOG) {
  if (p.hex) PAINT_COLORS['Citadel'][p.name] = p.hex
}
