// Hex aproximados de pinturas Citadel (color seco sobre blanco)
const PAINT_COLORS = {
  'Citadel': {
    // BASE
    'Abaddon Black':            '#231f20',
    'Averland Sunset':          '#f5a111',
    'Caledor Sky':              '#3e8dc0',
    'Caliban Green':            '#1a4e22',
    'Castellan Green':          '#3a5c35',
    'Ceramite White':           '#f8f8f8',
    'Corax White':              '#f0eeec',
    'Death Guard Green':        '#65763a',
    'Deathworld Forest':        '#516337',
    'Grey Seer':                '#c9c2b8',
    'Incubi Darkness':          '#154740',
    'Iron Hands Steel':         '#7a7d83',
    'Jokaero Orange':           '#e8581a',
    'Kantor Blue':              '#132457',
    'Khorne Red':               '#6b1111',
    'Leadbelcher':              '#828588',
    'Macragge Blue':            '#1b5082',
    'Mechanicus Standard Grey': '#5c6368',
    'Mephiston Red':            '#9e1b1b',
    'Mournfang Brown':          '#6b3219',
    'Naggaroth Night':          '#432c57',
    'Night Lords Blue':         '#142d68',
    'Orruk Flesh':              '#83a365',
    'Rakarth Flesh':            '#bfaa91',
    'Rhinox Hide':              '#472b1c',
    'Skavenblight Dinge':       '#6a6350',
    'Steel Legion Drab':        '#766b3c',
    'Stormvermin Fur':          '#847a6e',
    'Wraithbone':               '#e8d5a3',
    'XV-88':                    '#9e7c3c',
    'Zandri Dust':              '#c6a96b',

    // LAYER
    'Administratum Grey':       '#9d9d9d',
    'Altdorf Guard Blue':       '#254d9f',
    'Auric Armour Gold':        '#c9a837',
    'Balor Brown':              '#9e7530',
    'Brass Scorpion':           '#9e6a28',
    'Calgar Blue':              '#5979b5',
    'Dawnstone':                '#7d7d7e',
    'Eshin Grey':               '#4a4b4c',
    'Evil Sunz Scarlet':        '#c3342c',
    'Fenrisian Grey':           '#6e98c3',
    'Flash Gitz Yellow':        '#f0c825',
    'Fulgurite Copper':         '#a86035',
    "Gehenna's Gold":           '#c08820',
    'Hashut Copper':            '#9e5e30',
    'Hoeth Blue':               '#4a78b5',
    'Ironbreaker':              '#a3abb3',
    'Kabalite Green':           '#297059',
    'Kislev Flesh':             '#d4a87e',
    'Liberator Gold':           '#c99c30',
    'Longfang Grey':            '#6e8898',
    'Loren Forest':             '#4e7e38',
    'Moot Green':               '#42b549',
    'Pink Horror':              '#c84890',
    'Runefang Steel':           '#c5cdd5',
    'Screaming Skull':          '#d9c69c',
    'Sigmarite':                '#c8a050',
    'Skarsnik Green':           '#5c8e3e',
    'Skullcrusher Brass':       '#c09040',
    'Slaanesh Grey':            '#9a8fa1',
    'Sotek Green':              '#247d75',
    'Squig Orange':             '#d04828',
    'Stormhost Silver':         '#dce6ec',
    'Sybarite Green':           '#2e9464',
    'Temple Guard Blue':        '#2a9490',
    'Thunderhawk Blue':         '#3d6880',
    'Troll Slayer Orange':      '#e66e2e',
    'Ushabti Bone':             '#cbb87c',
    'Warboss Green':            '#4a8a3a',
    'Warpstone Glow':           '#3d9145',
    'White Scar':               '#f5f5f5',
    'Wild Rider Red':           '#d44c2c',
    'Yriel Yellow':             '#f5c020',
    'Zamesi Desert':            '#c09e50',

    // SHADE
    'Agrax Earthshade':         '#6e4a20',
    'Biel-Tan Green':           '#13682e',
    'Carroburg Crimson':        '#831533',
    'Casandora Yellow':         '#c5920c',
    'Coelia Greenshade':        '#19604a',
    'Drakenhof Nightshade':     '#1c3870',
    'Druchi Violet':            '#461557',
    'Fuegan Orange':            '#c05e18',
    'Nuln Oil':                 '#282828',
    'Reikland Fleshshade':      '#c07a40',
    'Seraphim Sepia':           '#c8932a',

    // DRY
    'Astorath Red':             '#a83028',
    'Changeling Pink':          '#d070a0',
    'Chronus Blue':             '#4878a8',
    'Eldar Flesh':              '#d4a87a',
    'Golgfag Brown':            '#a86030',
    'Hexos Palesun':            '#f0d878',
    'Imrik Blue':               '#3868b0',
    'Longbeard Grey':           '#b3b0a5',
    'Lucius Lilac':             '#a890b8',
    'Necron Compound':          '#a8b0b8',
    'Praxeti White':            '#f2f0ec',
    'Ryza Rust':                '#c05818',
    'Stormfang':                '#8090a8',
    'Terminatus Stone':         '#c8c0a0',
    'Tyrant Skull':             '#d4c898',
    'Underhive Ash':            '#a5a090',

    // CONTRAST
    'Aggaros Dunes':            '#c09845',
    'Aethermatic Blue':         '#4888c4',
    'Apothecary White':         '#ccd8dc',
    'Basilicanum Grey':         '#4a4a55',
    'Black Templar':            '#202022',
    'Blood Angels Red':         '#9e2820',
    'Dark Angels Green':        '#1d6832',
    'Darkoath Flesh':           '#b87858',
    'Flesh Tearers Red':        '#801818',
    'Gore-grunta Fur':          '#704838',
    'Gryph-charger Grey':       '#6878a0',
    'Gryph-hound Orange':       '#c85a18',
    'Iyanden Yellow':           '#d4a818',
    'Leviathan Purple':         '#502870',
    'Leviadon Blue':            '#1a3068',
    'Magos Purple':             '#7a3a9e',
    'Nazdreg Yellow':           '#d4a010',
    'Plaguebearer Flesh':       '#788840',
    'Shyish Purple':            '#5c2890',
    'Sigvald Burgundy':         '#6e1e38',
    'Skeleton Horde':           '#c4a458',
    'Snakebite Leather':        '#9e7235',
    'Space Wolves Grey':        '#7890b0',
    'Talassar Blue':            '#1a5888',
    'Terradon Turquoise':       '#1e7e84',
    'Ultramarines Blue':        '#1d4e9e',
    'Wyldwood':                 '#5c4a38',

    // TECHNICAL
    'Blood for the Blood God':  '#8e0e18',
    'Nihilakh Oxide':           '#28807a',
    "Nurgle's Rot":             '#6a9e18',
    'Nighthaunt Gloom':         '#488e98',
    'Typhus Corrosion':         '#3e3318',
    'Waystone Green':           '#38a870',
  }
}
