const fs = require('fs')
const path = require('path')

const TYPE_MAP = {
  'Acrylic Colors': 'base',
  'Metallic Colors': 'base',
  'Chameleon Colorshift Metallic': 'base',
  'Fluor Metallic': 'base',
  'Wash Ink': 'shade',
  'Dipping Inks': 'shade',
  'Intensity Ink': 'contrast',
  'Candy Ink Metallic': 'shade',
  'Matt Surface': 'spray',
  'Gloss Surface': 'spray',
}

const raw = [
  ['Abyss Blue','Acrylic Colors','#00134b'],
  ['Acid Green Dip','Dipping Inks','#455c0e'],
  ['Aether Blue','Wash Ink','#666ed0'],
  ['Amber Orange','Candy Ink Metallic','#f4b11a'],
  ['Amberglow Dip','Dipping Inks','#642d0f'],
  ['Amethyst Purple','Candy Ink Metallic','#d7a7f1'],
  ['Ancient Sepia','Wash Ink','#aaa168'],
  ['Andalusian Earth','Wash Ink','#766b59'],
  ['Anthrax Metal','Metallic Colors','#7b7e83'],
  ['Antique Gold','Metallic Colors','#957e38'],
  ['Aqua Turquoise','Metallic Colors','#9bd1d1'],
  ['Arachnid Green','Acrylic Colors','#124244'],
  ['Arctic Blue','Acrylic Colors','#14adcc'],
  ['Arrakis Brown','Acrylic Colors','#e39c28'],
  ['Atramentum Black','Wash Ink','#515151'],
  ['Azure Dip','Dipping Inks','#094448'],
  ['Banana Split','Acrylic Colors','#f0e229'],
  ['Barrel Grey','Acrylic Colors','#25221b'],
  ['Bestial Brown','Acrylic Colors','#2d1e01'],
  ['Black Green Stone Dip','Dipping Inks','#3e4639'],
  ['Black Stallion','Acrylic Colors','#000000'],
  ['Blackroot Grey','Acrylic Colors','#343436'],
  ['Blue','Fluor Metallic','#5e88ff'],
  ['Blue Glacier Dip','Dipping Inks','#53a7cb'],
  ['Bluebird Grey','Acrylic Colors','#6f657d'],
  ['Bluegrey Dusk','Acrylic Colors','#2a2c41'],
  ['Blush Red','Wash Ink','#db746d'],
  ['Blushing Flesh','Acrylic Colors','#da523a'],
  ['Borealis Green','Chameleon Colorshift Metallic','#7ac9d6'],
  ['Brown Skin','Acrylic Colors','#802709'],
  ['Burgundy Dip','Dipping Inks','#4f2330'],
  ['Burning Gold','Chameleon Colorshift Metallic','#f2de2f'],
  ['Caesar Red','Metallic Colors','#c8606b'],
  ['Camouflage Green','Acrylic Colors','#63601b'],
  ['Canary Green','Acrylic Colors','#d3dc65'],
  ['Carnage Red','Acrylic Colors','#c22b24'],
  ['Celestial Azure','Chameleon Colorshift Metallic','#7cc8d6'],
  ['Chancellor Blue','Acrylic Colors','#323045'],
  ['Choco Brown','Acrylic Colors','#3f2001'],
  ['Chrome Paint','Metallic Colors','#fcfdff'],
  ['Citrine Yellow','Candy Ink Metallic','#fff64f'],
  ['Cobalt Blue','Chameleon Colorshift Metallic','#4476d7'],
  ['Cool Blue Dip','Dipping Inks','#387971'],
  ['Coyote Brown','Acrylic Colors','#806b3e'],
  ['Crimson Magenta','Intensity Ink','#ff5a94'],
  ['Cutthroat Red','Acrylic Colors','#8e1316'],
  ['Cyber Yellow','Acrylic Colors','#f2d12c'],
  ['Dark Beige','Acrylic Colors','#715c41'],
  ['Dark Elder Bronze','Metallic Colors','#3e2c14'],
  ['Dark Umber','Acrylic Colors','#3b302e'],
  ['Darth Blue','Chameleon Colorshift Metallic','#4476d9'],
  ['Deck Grey','Acrylic Colors','#d1c2a3'],
  ['Deep Black Dip','Dipping Inks','#252525'],
  ['Desert Camo','Acrylic Colors','#947b3b'],
  ['Dusty Blue Dip','Dipping Inks','#2c4655'],
  ['Dusty Rose','Acrylic Colors','#f0636b'],
  ['Dwarven Flesh','Acrylic Colors','#ff7d4b'],
  ['El Dorado','Metallic Colors','#ba931c'],
  ['Elfwood Brown Dip','Dipping Inks','#4c361f'],
  ['Elven Flesh','Acrylic Colors','#f2aa82'],
  ['Ember Orange','Acrylic Colors','#d94a22'],
  ['Emerald Getaway','Chameleon Colorshift Metallic','#33ae92'],
  ['English Field Brown','Acrylic Colors','#6c4615'],
  ['Evil Forest','Chameleon Colorshift Metallic','#531516'],
  ['Faded Orange','Acrylic Colors','#f4793d'],
  ['Fang White','Acrylic Colors','#fffbdd'],
  ['Field Green-grey','Acrylic Colors','#1b4724'],
  ['Flaming Orange','Acrylic Colors','#ea701b'],
  ['Flesh Rose','Acrylic Colors','#d16855'],
  ['Flubber Green','Acrylic Colors','#88b719'],
  ['Forest Green','Acrylic Colors','#003910'],
  ['Foxhide Brown','Acrylic Colors','#c16001'],
  ['Gangrene','Acrylic Colors','#3b4312'],
  ['Garnet Purple Dip','Dipping Inks','#712f53'],
  ['Gengis Khaki','Acrylic Colors','#665b3b'],
  ['Gladius Bronze','Metallic Colors','#e1a767'],
  ['Glorious Magenta Dip','Dipping Inks','#7a2e4a'],
  ['Go Mango','Acrylic Colors','#ffa032'],
  ['Golden Cream','Acrylic Colors','#ffce53'],
  ['Gorgon Dark Green','Intensity Ink','#6ea87f'],
  ['Goth Skin Dip','Dipping Inks','#632d2b'],
  ['Green Ghost Dip','Dipping Inks','#1d5113'],
  ['Green Shark Skin Dip','Dipping Inks','#004542'],
  ['Grey Mist Dip','Dipping Inks','#787878'],
  ['Grey Teal','Acrylic Colors','#64857e'],
  ['Gunmetal Grey','Metallic Colors','#acb1b7'],
  ['Hellfire Red','Acrylic Colors','#cb160f'],
  ['Hulky Green Dip','Dipping Inks','#094625'],
  ['Hunter Green','Acrylic Colors','#017601'],
  ['Hydromiel Yellow','Intensity Ink','#f5f092'],
  ['Imperium Blue','Acrylic Colors','#1a3085'],
  ['Indigo Blue Dip','Dipping Inks','#1c2f59'],
  ['Ivory Tusk','Acrylic Colors','#f3dfbe'],
  ['Jade Green','Candy Ink Metallic','#9bffd4'],
  ['Komodo Khaki','Acrylic Colors','#885a29'],
  ['Kraken Green','Acrylic Colors','#034c39'],
  ['Lapislazuli','Acrylic Colors','#172c63'],
  ['Leather Brown','Acrylic Colors','#af6816'],
  ['Liche Purple','Acrylic Colors','#441c5a'],
  ['Lilac Purple','Acrylic Colors','#b076b3'],
  ['Lime','Fluor Metallic','#4eff71'],
  ['Limelight Dip','Dipping Inks','#605a02'],
  ['Lollipop Magenta','Acrylic Colors','#ab0061'],
  ['Majin Pink','Acrylic Colors','#d5618e'],
  ['Malefic Purple','Acrylic Colors','#110b49'],
  ['Marine Blue','Acrylic Colors','#12407e'],
  ['Martian Green','Chameleon Colorshift Metallic','#869b62'],
  ['Military Green','Acrylic Colors','#22260f'],
  ['Mint Twister','Acrylic Colors','#00baa3'],
  ['Mirage Blue','Acrylic Colors','#36455a'],
  ['Misted Yellow Dip','Dipping Inks','#8d611a'],
  ['Moon Mist Grey','Acrylic Colors','#dccfc9'],
  ['Moonstone Grey','Acrylic Colors','#8c8c8c'],
  ['Morrow Purple Dip','Dipping Inks','#786696'],
  ['Moss Green','Wash Ink','#6eac56'],
  ['Mustard Yellow','Acrylic Colors','#936611'],
  ['Mystic Gold','Chameleon Colorshift Metallic','#f2de2f'],
  ['Mystic White','Metallic Colors','#eff0f4'],
  ['Nebula Copper','Chameleon Colorshift Metallic','#c94fa6'],
  ['Neptunus Blue','Metallic Colors','#60baf8'],
  ['Nightshade Purple Dip','Dipping Inks','#472d5a'],
  ['Nuclear White','Acrylic Colors','#ffffff'],
  ['Nude Skin Dip','Dipping Inks','#de9390'],
  ['Ochre Desert','Acrylic Colors','#e08500'],
  ['Olive-brown Ops','Acrylic Colors','#372d0a'],
  ['Olivegrove Green','Acrylic Colors','#1b290f'],
  ['Opulentus Black','Intensity Ink','#515151'],
  ['Orange','Fluor Metallic','#f96e33'],
  ['Orchid Purple','Metallic Colors','#734472'],
  ['Ork Flesh Dip','Dipping Inks','#13331b'],
  ['Overlord Olive','Acrylic Colors','#37321f'],
  ['Pale Flesh','Acrylic Colors','#e8b9a7'],
  ['Papyrus Dip','Dipping Inks','#6e4e1b'],
  ['Parchment','Acrylic Colors','#e1c095'],
  ['Peach Flesh','Acrylic Colors','#e47700'],
  ['Pecatum Flesh','Wash Ink','#f4929f'],
  ['Persian Violet','Metallic Colors','#412480'],
  ['Phantom Violet','Acrylic Colors','#7d367c'],
  ['Phoenix Orange','Intensity Ink','#f1a760'],
  ['Pinky Blue','Chameleon Colorshift Metallic','#78cdd2'],
  ['Primer Black','Matt Surface','#1a1a1a'],
  ['Primer Green','Matt Surface','#485a04'],
  ['Primer Grey','Matt Surface','#cccccc'],
  ['Primer Red','Matt Surface','#882a1e'],
  ['Primer White','Matt Surface','#fdfdfd'],
  ['Prussian Blue','Acrylic Colors','#00416b'],
  ['Prussian Green','Acrylic Colors','#152e1b'],
  ['Psychotic Illusions','Chameleon Colorshift Metallic','#69acb5'],
  ['Purple Vanity Dip','Dipping Inks','#392e56'],
  ['Quartz Magenta','Candy Ink Metallic','#ea86aa'],
  ['Quicksand Brown','Acrylic Colors','#7d4a1b'],
  ['Quicksilver','Metallic Colors','#e0e3e8'],
  ['Radiant Orange Dip','Dipping Inks','#844406'],
  ['Ranger Green','Acrylic Colors','#38352e'],
  ['Red','Fluor Metallic','#f03c25'],
  ['Red Cloak Dip','Dipping Inks','#b2655d'],
  ['Red Goblin','Chameleon Colorshift Metallic','#a9ba73'],
  ['Red Opulence Dip','Dipping Inks','#bb2320'],
  ['Red Truth','Acrylic Colors','#ec2005'],
  ['Redwood Brown','Acrylic Colors','#3e0d00'],
  ['Rocket Green','Acrylic Colors','#415e24'],
  ['Rose','Fluor Metallic','#f470a1'],
  ['Rotten Green','Acrylic Colors','#77932c'],
  ['Royal Burgundy','Chameleon Colorshift Metallic','#90a375'],
  ['Ruby Red','Candy Ink Metallic','#f5904c'],
  ['Sacra Purple','Intensity Ink','#8869b9'],
  ['Sandstorm','Acrylic Colors','#bf9f66'],
  ['Sangria Red','Acrylic Colors','#5e0a0a'],
  ['Sanguinem Red','Intensity Ink','#ff6050'],
  ['Sapphire Blue','Candy Ink Metallic','#acc9ff'],
  ['Scorched Wood','Acrylic Colors','#24110a'],
  ['Sepia Vetus','Intensity Ink','#aba269'],
  ['Seraphim Flesh Dip','Dipping Inks','#bc6f51'],
  ['Sharkfin Blue','Metallic Colors','#95caf6'],
  ['Shiny Gold','Metallic Colors','#bfa22c'],
  ['Sirenscale Green','Metallic Colors','#05c18e'],
  ['Skeleton Brown Dip','Dipping Inks','#4e3e25'],
  ['Skull Linen Dip','Dipping Inks','#a2a19d'],
  ['Slate Grey','Acrylic Colors','#565656'],
  ['Smoked Blue','Acrylic Colors','#55677f'],
  ['Solar Anomalie','Chameleon Colorshift Metallic','#d154a2'],
  ['Starship Grey','Acrylic Colors','#7d6c72'],
  ['Steampunk Copper','Metallic Colors','#dda37e'],
  ['Steel Grey','Acrylic Colors','#2a333c'],
  ['Storm Surge Green','Chameleon Colorshift Metallic','#61a694'],
  ['Summersea Blue','Acrylic Colors','#0268b0'],
  ['Sun-bleached Bone','Acrylic Colors','#d1904e'],
  ['Swamp Brown','Intensity Ink','#a85d46'],
  ['Temple Ochre','Acrylic Colors','#ca9f5b'],
  ['Tenebris Blue','Intensity Ink','#676fd1'],
  ['Tiger Brown','Acrylic Colors','#f19200'],
  ['Tiger Eye Brown','Candy Ink Metallic','#e8c196'],
  ['Tinmetal Grey','Metallic Colors','#b9adad'],
  ['Toxic Purple','Chameleon Colorshift Metallic','#7a398d'],
  ['Tropical Green','Chameleon Colorshift Metallic','#b3d924'],
  ['Tropical Turquoise','Acrylic Colors','#33afa5'],
  ['Turquoise Ghost Dip','Dipping Inks','#055145'],
  ['Ultramar Blue','Acrylic Colors','#343468'],
  ['Valkyrie Yellow','Acrylic Colors','#e7d96c'],
  ['Vanilla Drop','Acrylic Colors','#fee591'],
  ['Vicious Purple','Wash Ink','#8767ba'],
  ['Violet','Fluor Metallic','#be68e3'],
  ['Violet Hint Dip','Dipping Inks','#9a82bc'],
  ['Viridian Green','Acrylic Colors','#019a88'],
  ['Viridis Green','Intensity Ink','#5aa38f'],
  ['Walnut Brown','Intensity Ink','#776c5a'],
  ['Warcry Green','Acrylic Colors','#3e6121'],
  ['White','Fluor Metallic','#ffffff'],
  ['Whitecap Beige','Acrylic Colors','#d6c4b0'],
  ['Wolven Grey','Acrylic Colors','#b0b6c6'],
  ['Wonka Violet','Acrylic Colors','#771641'],
  ['Yellow','Fluor Metallic','#f8fb48'],
  ['Yellow Submarine Dip','Dipping Inks','#bd9c0f'],
  ['Yellow-brown Ops','Acrylic Colors','#8a5e21'],
  ['Yellow-orange','Fluor Metallic','#f89d68'],
  ['Yoda Green','Acrylic Colors','#557c5d'],
  ['Zima Blue','Acrylic Colors','#48a3c0'],
  ['Zombie Dip','Dipping Inks','#373b22'],
  ['Zombie Flesh','Acrylic Colors','#c9ac6a'],
]

const paints = []
const seen = new Set()
for (const [name, set, hex] of raw) {
  const type = TYPE_MAP[set] || 'base'
  const key = name.toLowerCase() + '|' + type
  if (seen.has(key)) continue
  seen.add(key)
  paints.push({ name, hex, type })
}

function pad(s, n) { return s + ' '.repeat(Math.max(0, n - s.length)) }
const maxName = Math.max(...paints.map(p => p.name.length)) + 2
const lines = paints.map(p => {
  const namePart = pad("'" + p.name.replace(/'/g, "\\'") + "',", maxName + 1)
  return `  { name: ${namePart}hex: '${p.hex}', type: '${p.type}' },`
})

const content = `// Green Stuff World — generado desde github.com/Arcturus5404/miniature-paints\nexport const GREEN_STUFF_WORLD = [\n${lines.join('\n')}\n]\n`
fs.writeFileSync(path.join(__dirname, '..', 'src', 'paint-catalog-gsw.js'), content)
console.log('Total pinturas GSW:', paints.length)
