export const state = {
  games: [],
  factions: [],
  units: [],
  unitMap: {},
  typeMap: {},
  minisActuales: [],
  wishlistActuales: [],
  pinturas: [],
  miniEnEdicion: null,
  paintEnEdicion: null,
  tabActual: 'coleccion',
  pendingPhotoFile: null,
  pendingPhotoRemove: false,
  filtroNombre: '',
  filtroType: '',
  ordenar: 'reciente',
  sortDir: 'desc',
  cameraStream: null,
  cameraPendingPaint: null,
  cameraContext: 'catalog',
}
